/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Schooling.UI;

import Schooling.Model.JobPortal;
import Schooling.Model.JobPortalStudent;
import Student.Student;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author navinsharma
 */
public class JobPortal_Student_Apply extends javax.swing.JPanel {

    /**
     * Creates new form JobPortal_Student_Apply
     */
    JPanel controlArea;
    JPanel workArea;
    ResultSet resultSet;
    int student_id;
    String company_name, job_title, job_type, location, job_description, category;
    JobPortal jp = new JobPortal();
    public JobPortal_Student_Apply(JPanel controlArea, JPanel workArea, int student_id) 
    {
        try 
        {
            initComponents();
            this.student_id = student_id;
            this.controlArea = controlArea;
            this.workArea = workArea;
            JobPortal jp = new JobPortal();
            resultSet = jp.getallJobs();
            ViewTable();
        } 
        catch (SQLException ex) 
        {
//            Logger.getLogger(JobPortal_Read.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonView = new javax.swing.JButton();
        jButtonApply = new javax.swing.JButton();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jLabelLocation = new javax.swing.JLabel();
        jLabelJobDescription = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabelCompanyName = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jComboBoxJobType = new javax.swing.JComboBox<>();
        jLabelTitle = new javax.swing.JLabel();
        jLabelJobType = new javax.swing.JLabel();
        jTextFieldJobTitle = new javax.swing.JTextField();
        jScrollPaneJobDescription = new javax.swing.JScrollPane();
        jTextAreaJobDescription = new javax.swing.JTextArea();
        jLabelJobTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 224, 206));

        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jButtonApply.setText("Apply");
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On Campus", "Off Campus" }));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jLabelLocation.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        jLabelLocation.setText("Location:");

        jLabelJobDescription.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        jLabelJobDescription.setText("Job Description:");

        jLabelCategory.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        jLabelCategory.setText("Category:");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Company name", "Job title", "Category", "Job Type", "Location", "Job description"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabelCompanyName.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        jLabelCompanyName.setText("Company Name:");

        jComboBoxJobType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Part time", "Full time", "Intern" }));

        jLabelTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Job Portal : Read Jobs");

        jLabelJobType.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        jLabelJobType.setText("Job Type:");

        jTextAreaJobDescription.setColumns(20);
        jTextAreaJobDescription.setRows(5);
        jScrollPaneJobDescription.setViewportView(jTextAreaJobDescription);

        jLabelJobTitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        jLabelJobTitle.setText("Job Title:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Job portal.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(96, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelCompanyName)
                                            .addComponent(jLabelJobDescription)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelJobType)
                                                        .addComponent(jLabelLocation))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelJobTitle)
                                                        .addComponent(jLabelCategory)))
                                                .addGap(42, 42, 42)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPaneJobDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBoxJobType, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(70, 70, 70)
                                        .addComponent(jButtonApply, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTitle)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCompanyName)
                            .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonView))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonApply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJobTitle)
                    .addComponent(jTextFieldJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategory)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxJobType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJobType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocation)
                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneJobDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelJobDescription)))
                .addGap(113, 113, 113))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        String category;

        category = jComboBoxCategory.getSelectedItem().toString();
        if("Off Campus".equals(category))
        {
            jComboBoxJobType.addItem("Part time");
            jComboBoxJobType.addItem("Full time");
            jComboBoxJobType.addItem("Intern");
        }
        else
        {
            jComboBoxJobType.removeAllItems();
        }
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable.getSelectedRow();
        if (selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
        }
        else
        {
            DefaultTableModel table_model = (DefaultTableModel) jTable.getModel();
            jTextFieldCompanyName.setText(table_model.getValueAt(selectedRowIndex, 0).toString());
            jTextFieldJobTitle.setText(table_model.getValueAt(selectedRowIndex, 1).toString());
            if("On Campus".equals(table_model.getValueAt(selectedRowIndex, 2).toString()))
            {
                jComboBoxCategory.setSelectedItem("On Campus");
            }
            else
            {
                jComboBoxCategory.setSelectedItem("Off Campus");
            }
            if("Part time".equals(table_model.getValueAt(selectedRowIndex, 3).toString()))
            {
                jComboBoxJobType.setSelectedItem("Part time");
            }
            if("Full time".equals(table_model.getValueAt(selectedRowIndex, 3).toString()))
            {
                jComboBoxJobType.setSelectedItem("Full time");
            }
            else
            {
                jComboBoxJobType.setSelectedItem("Intern");
            }
            jTextFieldLocation.setText(table_model.getValueAt(selectedRowIndex, 4).toString());
            jTextAreaJobDescription.setText(table_model.getValueAt(selectedRowIndex, 5).toString());
        }
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        // TODO add your handling code here:
        String company_name2, job_title2, job_type2, location2, job_description2, category2;
        ResultSet resultSet1, resultSet2;

        company_name2 = jTextFieldCompanyName.getText();
        if(company_name2.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Company name cannot be null.");
        }
        else
        {
            job_title2 = jTextFieldJobTitle.getText();
            if(job_title2.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Job title cannot be null.");
            }
            else
            {
                category2 = jComboBoxCategory.getSelectedItem().toString();
                if("Off Campus".equals(category2))
                {
                    job_type2 = jComboBoxJobType.getSelectedItem().toString();
                }
                else
                {
                    job_type2 = "";
                }
                location2 = jTextFieldLocation.getText();
                if (location2.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Location cannot be null.");
                }
                else
                {
                    job_description2 = jTextAreaJobDescription.getText();
                    if (job_description2.isEmpty())
                    {
                        JOptionPane.showMessageDialog(this, "Job description cannot be null.");
                    }
                    else
                    {
                        try
                        {
                            resultSet1 = jp.getallJobs();
                            while(resultSet1.next())
                            {
                                if(resultSet1.getString(2).equals(company_name) &&
                                    resultSet1.getString(3).equals(job_title) &&
                                    resultSet1.getString(4).equals(category) &&
                                    resultSet1.getString(5).equals(job_type) &&
                                    resultSet1.getString(6).equals(location) &&
                                    resultSet1.getString(7).equals(job_description))
                                {
                                    int id = resultSet1.getInt(1);
                                    JobPortalStudent jps = new JobPortalStudent(student_id, id);
                                    jps.addJob(student_id, id);
                                }
                            }
                        }
                        catch (SQLException ex)
                        {
//                            Logger.getLogger(JobPortal_Add.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonApplyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApply;
    private javax.swing.JButton jButtonView;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxJobType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelCompanyName;
    private javax.swing.JLabel jLabelJobDescription;
    private javax.swing.JLabel jLabelJobTitle;
    private javax.swing.JLabel jLabelJobType;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneJobDescription;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextAreaJobDescription;
    private javax.swing.JTextField jTextFieldCompanyName;
    private javax.swing.JTextField jTextFieldJobTitle;
    private javax.swing.JTextField jTextFieldLocation;
    // End of variables declaration//GEN-END:variables

    private void ViewTable() throws SQLException
    {
        DefaultTableModel table_model = (DefaultTableModel) jTable.getModel();
        table_model.setRowCount(0);
        
        try 
        {
            while (resultSet.next()) 
            {
                Object[] row = new Object[6];
                row[0] = resultSet.getString(2);
                row[1] = resultSet.getString(3);
                row[2] = resultSet.getString(4);
                row[3] = resultSet.getString(5);
                row[4] = resultSet.getString(6);
                row[5] = resultSet.getString(7);
                table_model.addRow(row);
            }
        } 
        catch (IllegalArgumentException e) 
        {
            throw new IllegalArgumentException(e.getMessage() + "Record not found");
        }
    }
}
