/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Schooling.UI;

import Schooling.Model.JobPortal;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author navinsharma
 */
public class JobPortal_Add extends javax.swing.JPanel {

    /**
     * Creates new form JobPortal_Delete
     */
    JPanel controlArea;
    JPanel workArea;
    public JobPortal_Add(JPanel controlArea, JPanel workArea) {
        initComponents();
        this.controlArea = controlArea;
        this.workArea = workArea;
        jComboBoxJobType.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxJobType = new javax.swing.JComboBox<>();
        jLabelJobType = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jTextFieldJobTitle = new javax.swing.JTextField();
        jLabelCategory = new javax.swing.JLabel();
        jLabelJobTitle = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPaneJobDescription = new javax.swing.JScrollPane();
        jTextAreaJobDescription = new javax.swing.JTextArea();
        jLabelJobDescription = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jLabelLocation = new javax.swing.JLabel();
        jTextFieldCompanyName = new javax.swing.JTextField();
        jLabelCompanyName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 224, 206));
        setLayout(null);

        add(jComboBoxJobType);
        jComboBoxJobType.setBounds(394, 231, 235, 23);

        jLabelJobType.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabelJobType.setText("Job Type:");
        add(jLabelJobType);
        jLabelJobType.setBounds(237, 233, 125, 17);

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On Campus", "Off Campus" }));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });
        add(jComboBoxCategory);
        jComboBoxCategory.setBounds(394, 190, 235, 23);
        add(jTextFieldJobTitle);
        jTextFieldJobTitle.setBounds(394, 149, 235, 23);

        jLabelCategory.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabelCategory.setText("Category:");
        add(jLabelCategory);
        jLabelCategory.setBounds(241, 192, 121, 17);

        jLabelJobTitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabelJobTitle.setText("Job Title:");
        add(jLabelJobTitle);
        jLabelJobTitle.setBounds(241, 151, 123, 17);

        jButtonSubmit.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        add(jButtonSubmit);
        jButtonSubmit.setBounds(467, 422, 84, 23);

        jLabelTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Job Portal : Add Job");
        add(jLabelTitle);
        jLabelTitle.setBounds(0, 25, 862, 50);

        jTextAreaJobDescription.setColumns(20);
        jTextAreaJobDescription.setRows(5);
        jScrollPaneJobDescription.setViewportView(jTextAreaJobDescription);

        add(jScrollPaneJobDescription);
        jScrollPaneJobDescription.setBounds(394, 313, 235, 91);

        jLabelJobDescription.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabelJobDescription.setText("Job Description:");
        add(jLabelJobDescription);
        jLabelJobDescription.setBounds(237, 349, 125, 17);
        add(jTextFieldLocation);
        jTextFieldLocation.setBounds(394, 272, 235, 23);

        jLabelLocation.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabelLocation.setText("Location:");
        add(jLabelLocation);
        jLabelLocation.setBounds(237, 274, 125, 17);
        add(jTextFieldCompanyName);
        jTextFieldCompanyName.setBounds(394, 108, 235, 23);

        jLabelCompanyName.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        jLabelCompanyName.setText("Company Name:");
        add(jLabelCompanyName);
        jLabelCompanyName.setBounds(241, 110, 123, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Job portal.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(60, 40, 720, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        String company_name, job_title, job_type, location, job_description, category;
        
        company_name = jTextFieldCompanyName.getText();
        if(company_name.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Company name cannot be null.");
        }
        else
        {
            job_title = jTextFieldJobTitle.getText();
            if(job_title.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Job title cannot be null.");
            }
            else
            {
                category = jComboBoxCategory.getSelectedItem().toString();
                if("Off Campus".equals(category))
                {
                    job_type = jComboBoxJobType.getSelectedItem().toString();
                }
                else
                {
                    job_type = "";
                }
                location = jTextFieldLocation.getText();
                if (location.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Location cannot be null.");
                } 
                else 
                {
                    job_description = jTextAreaJobDescription.getText();
                    if (job_description.isEmpty()) 
                    {
                        JOptionPane.showMessageDialog(this, "Job description cannot be null.");
                    } 
                    else 
                    {
                        try 
                        {
                            JobPortal jp = new JobPortal(company_name, job_title, category, job_type, location, job_description);
                            jp.addJob(company_name, job_title, category, job_type, location, job_description);
                        } 
                        catch (SQLException ex)
                        {
//                            Logger.getLogger(JobPortal_Add.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        String category;
        
        category = jComboBoxCategory.getSelectedItem().toString();
        if("Off Campus".equals(category))
        {
            jComboBoxJobType.addItem("Part time");
            jComboBoxJobType.addItem("Full time");
            jComboBoxJobType.addItem("Intern");
        }
        else
        {
            jComboBoxJobType.removeAllItems();
        }
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxJobType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelCompanyName;
    private javax.swing.JLabel jLabelJobDescription;
    private javax.swing.JLabel jLabelJobTitle;
    private javax.swing.JLabel jLabelJobType;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPaneJobDescription;
    private javax.swing.JTextArea jTextAreaJobDescription;
    private javax.swing.JTextField jTextFieldCompanyName;
    private javax.swing.JTextField jTextFieldJobTitle;
    private javax.swing.JTextField jTextFieldLocation;
    // End of variables declaration//GEN-END:variables
}
