/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Schooling.UI;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author navinsharma
 */
public class Schooling_University extends javax.swing.JPanel {

    /**
     * Creates new form Schooling_University
     */
    JPanel controlArea;
    JPanel workArea;
    public Schooling_University(JPanel controlArea, JPanel workArea) {
        initComponents();
        this.controlArea = controlArea;
        this.workArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonManageFieldOfInterest = new javax.swing.JButton();
        jButtonManageCourses = new javax.swing.JButton();
        jButtonManageUIniversity = new javax.swing.JButton();

        jButtonManageFieldOfInterest.setText("Manage Field Of Interest");
        jButtonManageFieldOfInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFieldOfInterestActionPerformed(evt);
            }
        });

        jButtonManageCourses.setText("Manage Courses");
        jButtonManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageCoursesActionPerformed(evt);
            }
        });

        jButtonManageUIniversity.setText("Manage University");
        jButtonManageUIniversity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageUIniversityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonManageUIniversity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonManageCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonManageFieldOfInterest))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonManageUIniversity)
                .addGap(47, 47, 47)
                .addComponent(jButtonManageCourses)
                .addGap(48, 48, 48)
                .addComponent(jButtonManageFieldOfInterest)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManageUIniversityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageUIniversityActionPerformed
        // TODO add your handling code here:
        University_ManageUniversity umu = new University_ManageUniversity(controlArea, workArea);
        controlArea.add("University_ManageUniversity",umu);
        CardLayout layout = (CardLayout)controlArea.getLayout();
        layout.next(controlArea); 
    }//GEN-LAST:event_jButtonManageUIniversityActionPerformed

    private void jButtonManageFieldOfInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFieldOfInterestActionPerformed
        // TODO add your handling code here:
        University_ManageFieldOfInterest mfoi = new University_ManageFieldOfInterest(controlArea, workArea);
        controlArea.add("University_ManageFieldOfInterest",mfoi);
        CardLayout layout = (CardLayout)controlArea.getLayout();
        layout.next(controlArea); 
    }//GEN-LAST:event_jButtonManageFieldOfInterestActionPerformed

    private void jButtonManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageCoursesActionPerformed
        // TODO add your handling code here:
        University_ManageCourses umc = new University_ManageCourses(controlArea, workArea);
        controlArea.add("University_ManageCourses",umc);
        CardLayout layout = (CardLayout)controlArea.getLayout();
        layout.next(controlArea); 
    }//GEN-LAST:event_jButtonManageCoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonManageCourses;
    private javax.swing.JButton jButtonManageFieldOfInterest;
    private javax.swing.JButton jButtonManageUIniversity;
    // End of variables declaration//GEN-END:variables
}
