/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Schooling;

/**
 *
 * @author navinsharma
 */
public class Schooling_Admin extends javax.swing.JPanel {

    /**
     * Creates new form Schooling_Admin
     */
    public Schooling_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelLeft = new javax.swing.JPanel();
        jButtonJobPortal = new javax.swing.JButton();
        jButtonPersonalOrganization = new javax.swing.JButton();
        jButtonUniversities = new javax.swing.JButton();
        jButtonManageDepartments = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();

        jButtonJobPortal.setText("Job Portal");
        jButtonJobPortal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJobPortalActionPerformed(evt);
            }
        });

        jButtonPersonalOrganization.setText("Personal Organization");
        jButtonPersonalOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonalOrganizationActionPerformed(evt);
            }
        });

        jButtonUniversities.setText("Universities");
        jButtonUniversities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUniversitiesActionPerformed(evt);
            }
        });

        jButtonManageDepartments.setText("Manage Departments");
        jButtonManageDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageDepartmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonJobPortal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPersonalOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUniversities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonManageDepartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButtonJobPortal)
                .addGap(50, 50, 50)
                .addComponent(jButtonPersonalOrganization)
                .addGap(50, 50, 50)
                .addComponent(jButtonUniversities)
                .addGap(50, 50, 50)
                .addComponent(jButtonManageDepartments)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanelLeft);

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanelRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJobPortalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJobPortalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonJobPortalActionPerformed

    private void jButtonPersonalOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonalOrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPersonalOrganizationActionPerformed

    private void jButtonManageDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageDepartmentsActionPerformed
        // TODO add your handling code here:
        Schooling_ManageDepartments md = new Schooling_ManageDepartments();
        jSplitPane1.setRightComponent(md);
    }//GEN-LAST:event_jButtonManageDepartmentsActionPerformed

    private void jButtonUniversitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUniversitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUniversitiesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJobPortal;
    private javax.swing.JButton jButtonManageDepartments;
    private javax.swing.JButton jButtonPersonalOrganization;
    private javax.swing.JButton jButtonUniversities;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
